### ISSUE TITLE
Xref data sources to be added to BridgeDb

### ISSUE THREAD

**Issue by Finterly** [PathVisio/libGPML#1]
Here we keep a list of Xref data sources (and their occurrences) that have been used in GPML2013a but are not in BridgeDb datasources.tsv. Some datasources are duplicates of existing ones, save for spelling, and will be fixed by curation.  

- [x] PubChem Compound: 1: false
- [x] ChemIDplus: 10: false
- [x] Ensembl Plants: 118: false
- [ ] pato: 10: false
- [x] GeneDB: 1: false
- [x] Uniprot/TrEMBL: 1: false
- [x] Kegg ortholog: 45: false
- [x] COMPOUND: 9: false
- [ ] NanoParticle Ontology: 9: false
- [x] Ensembl Mosquito: 1: false
- [x] PubChem: 3: false
- [x] Kegg Compound: 1: false
- [x] Uniprot-SwissProt: 15: false
- [x] RiceCyc: 4: false
- [x] Entrez: 2: false

**Comment by egonw** [comment]
The Curated analysis seems okay (except for http://www.wikipathways.org/instance/WP2235_r118343 which I'll fix now):

```sparql
SELECT DISTINCT ?node ?source ?homepage
WHERE {
  VALUES ?source {
    "PubChem" "PubChem Compound" "ChemIDplus" "Ensembl Plants"
    "GeneDB" "Uniprot/TrEMBL" "Kegg ortholog" "COMPOUND"
    "Ensembl Mosquito" "Kegg Compound" "Uniprot-SwissProt"
    "RiceCyc" "Entrez"
  }
  ?node gpml:xrefDataSource ?source ;
        dcterms:isPartOf ?gpmlpw .
  ?wppw wp:isAbout ?gpmlpw ;
        foaf:page ?homepage .
}
```

Run: https://bit.ly/3W1iWPs

**Comment by egonw** [comment]
Converted into a unit test: https://github.com/wikipathways/WikiPathwaysCurator/commit/1850e069cad642ef9f83932e58e6ece29acd8fab

**Comment by egonw** [comment]
Okay, finally the job ran on Analysis/Curation. All fine. Any remaining (in ALL) will be fixed in the next week or two.

**Comment by egonw** [comment]
Results of ALL:

![image](https://user-images.githubusercontent.com/26721/206853246-4ff89cc8-9330-46b6-ae6a-e31e7c361d0f.png)
